### ISSUE TITLE
Can a namespace exotic be exported as the default?

### ISSUE THREAD

**Issue by loganfsmyth** [leebyron/ecmascript-export-ns-from#1]
Babel doesn't currently parse it, and I was curious, since it seems like it should for symmetry, e.g.

```
export * as foo from 'foo';
```

becomes

```
import * as _tmp from 'foo';
export {_tmp as foo};
```

Should

```
export * as default from 'foo';
```

behave as

```
import * as _tmp from 'foo';
export {_tmp as default};
```

?

**Comment by caridy** [comment]
It certainly can be! There is nothing in the spec to prevent this from being a valid production, and has you have figured already, it is perfectly doable with the existing grammar, just a little bit tedious.

But the question is: do we want to facilitate it? I will say, _no_! One of the guiding principles here is to optimize for the good practices, and make it hard for the bad! And exporting a NS as the default export is smelly, and has some perf implications.

**Comment by leebyron** [comment]
Babel has a plugin for enabling this proposal actually, and it should work as you describe :)

**Comment by loganfsmyth** [comment]
@caridy I agree it's probably not a great ideal to export a namespace exotic as a default, but from the standpoint of symmetry and consistency it seems like it would be surprising if you couldn't do it.

@leebyron Oh I know, Babel currently throws a parse error if you use `default` and it wasn't obvious from the current proposal text whether that was intended or an oversight. I'll update Babel to support `default` as an identifier then.

**Comment by caridy** [comment]
@loganfsmyth not sure what you mean with symmetry, but we certainly care about the reflective form to create modules that are equivalent to this, and via the reflective api you could certainly do this as well:

``` js
let ns = new Reflect.Module({
    foo: Reflect.Module.Export.const(myOtherNamespaceObj)
});
// where ns.foo is an immutable reference to myOtherNamespaceObj.
```

:)

**Comment by loganfsmyth** [comment]
@caridy Sorry, could have been clearer, I meant consistency with other forms of export. "Symmetry" following the definition in the proposal: https://github.com/leebyron/ecmascript-export-ns-from#symmetry-between-import-and-export

So since `import {foo as bar} from 'foo'` can map an export to a local binding, and `export {foo as default} from 'foo';` can map an export to a default export, it feels expected that `import * as bar from 'foo';` would map similarly to `export * as default from 'foo';`.

**Comment by benjamn** [comment]
@loganfsmyth Are you planning to release the `* as default` fix in Babylon?

**Comment by loganfsmyth** [comment]
I honestly 100% forgot this issue. Filed: https://github.com/babel/babylon/issues/469
