### ISSUE TITLE
Still stage 1?

### ISSUE THREAD

**Issue by stevenvachon** [leebyron/ecmascript-export-ns-from#17]
What can be done to move this forward? I think it's important.

**Comment by ljharb** [comment]
This proposal has moved to a needs-consensus PR: https://github.com/tc39/ecma262/pull/1174

**Comment by spectranaut** [comment]
Closing - the consensus PR was merged: https://github.com/tc39/ecma262/pull/1174 :tada:

**Comment by stevenvachon** [comment]
Does that mean this is now stage 4?

**Comment by ljharb** [comment]
It means it changed to a needs-consensus PR, which means it's not a proposal and has no stages.

**Comment by stevenvachon** [comment]
When someone has a chance, please update the readme to reflect this.
