### ISSUE TITLE
ParseModule semantics change

### ISSUE THREAD

**Issue by rhettlivingston** [leebyron/ecmascript-export-ns-from#3]
I don't know that this is the appropriate place, but this is essentially an issue (probably more of a reminder) against the document at http://leebyron.com/ecmascript-export-ns-from/.

Step 11.b of section '15.2.1.16.1 ParseModule ( sourceText, realm, hostDefined )' of the specification currently states

```
11. ...
  b. Else if ee.[[ImportName]] is "*", then
    i. Append ee to starExportEntries.
```

While inserting support for `export * as ns from ...` into some code tightly following this portion of the specification and your specification modifications at http://leebyron.com/ecmascript-export-ns-from/, I found this caused the resultant exportEntry to be placed in starExportEntries instead of indirectExportEntries.

I believe this is incorrect because we have an exportName and thus GetExportedNames will not need to visit the original exporting module to determine exported names.

I fixed my code by changing it to the equivalent of

```
11. ...
  b. Else if ee.[[ExportName]] is null and ee.[[ImportName]] is "*", then
    i. Append ee to starExportEntries.
```

**Comment by spectranaut** [comment]
This was eventually resolved in the PR, good catch from a long time ago.

Closing this issue as the PR has been merged: https://github.com/tc39/ecma262/pull/1174
